# Generated by Django 4.2.3 on 2025-10-28 07:49

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="schools", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
