# Generated by Django 4.2.3 on 2025-10-28 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="teachingSchools", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
