# Generated by Django 4.2.3 on 2025-10-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0002_school_teachers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentTeacherInvites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacherInvites",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
