# Generated by Django 4.2.3 on 2025-10-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_teacherinvite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherinvite",
            old_name="invited_by",
            new_name="invitedBy",
        ),
    ]
