# Generated by Django 4.2.3 on 2025-10-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_profilepictureurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lastViewedPopupAt",
        ),
    ]
