# Generated by Django 4.2.3 on 2025-10-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
