# Generated by Django 4.2.3 on 2025-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("teacher-admin", "Teacher Admin"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=16,
            ),
        ),
    ]
