# Generated by Django 4.2.3 on 2025-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_isstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profilePictureUrl",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
