EDUCATION_TYPES = [
    "EGU med EUD-fagelementer",
    "FGU-kombi (AGU/PGU-spor) med eud-fagelementer",
    "FGU-kombi (EGU-spor) med eud-fagelementer",
    "Klejnsmed",
    "Smed - bearbejdning",
    "Energiteknik",
    "Smed - maritim",
    "Smed - rustfast",
    "Svejser",
    "Skibsmekaniker",
    "Skibsmontør",
    "Industrimontør",
    "Støberiassistent",
    "Støberitekniker",
    "Beslagsmed",
    "Industrioperatør",
    "Industrioperatør, produktivitet",
    "Overfladebehandler",
    "Overfladebehandler - konstruktioner",
    "Overfladebehandler - industrilakering",
    "Værktøjsmager",
    "Værktøjskonstruktør",
    "Finmekaniker",
    "Våbenmekaniker",
    "Låsesmed",
    "Finmekanikerassistent",
    "Køletekniker",
    "Køleassistent",
    "Industritekniker-produktion",
    "Industritekniker-maskin",
    "Industriassistent",
    "Datatekniker med speciale i infrastruktur",
    "Datatekniker med speciale i programmering",
    "Datatekniker med speciale i cybersikkerhed",
    "It-supporter",
    "Elektronikfagtekniker",
    "Radio-tv-fagtekniker",
    "Medicotekniker",
    "Elektronik udviklingstekniker",
    "Automatiktekniker",
    "Automatiktekniker i elektrobranchen",
    "Automatikmontør",
    "Elevatortekniker",
    "Automatiseringstekniker",
    "Entreprenørmaskinmekaniker",
    "Landbrugsmaskinmekaniker",
    "Kranmekaniker",
    "Landbrugssmed",
    "Materielmekaniker",
    "Personliftmekaniker",
    "Karrosseritekniker - bygger",
    "Karrosseritekniker - opretter",
    "Lufthavnsoperatør - Cleaning",
    "Lufthavnsoperatør - Ground handling",
    "Lufthavnsoperatør - Bagage loading",
    "Lufthavnsoperatør - Bagage sorting",
    "Lufthavnsoperatør med speciale i disponering",
    "Lufthavnsoperatør - Cargo",
    "Lufthavnsoperatør - Aircraft servicing",
    "Lufthavnsoperatør - Airport service",
    "Lufthavnsoperatør - Brand og redning",
    "Lufthavnsoperatør - Fuel",
    "Cykelmekaniker",
    "Motorcykelmekaniker",
    "Knallertmekaniker",
    "B1-flytekniker, mekanik",
    "B2-flytekniker, elektronik",
    "Bestiksølvsmed",
    "Butiksguldsmed",
    "Ædelstensfatter",
    "Ciselør",
    "Guldsmed",
    "Korpussølvsmed",
    "Montageoperatør",
    "Kompositoperatør",
    "Bådebygger",
    "Sejlmager",
    "Plastmager med speciale i termoplast",
    "Specialist i plastproduktion",
    "Plastoperatør",
    "Audiologiassistent",
    "Neurofysiologiassistent",
    "Procesarbejder",
    "Procesoperatør",
    "Procesoperatør med spec. pharma&fødevareingrediens",
    "Procesoperatør med spec i grøn energi & produktion",
    "Tagdækker",
    "Murer",
    "Forsyningsoperatør",
    "Stenhugger",
    "Stentekniker",
    "Stukkatør",
    "Brolægger",
    "Bygningsstruktør",
    "Anlægsstruktør",
    "Tømrer",
    "Gulvlægger",
    "Tækkemand",
    "Alubygger",
    "Glarmester",
    "Bygningssnedker",
    "Møbelsnedker",
    "Orgelbygger",
    "Maskinsnedker",
    "Produktionsassistent, døre og vinduer",
    "Produktionsassistent, møbel",
    "Ventilationstekniker",
    "Vvs-installationstekniker",
    "Blikkenslager og vvs",
    "Vvs-energispecialist",
    "Teknisk isolatør",
    "Elektriker 1",
    "Elektriker 2",
    "Skorstensfejer",
    "Ejendomsservicetekniker",
    "Bygningsmaler",
    "Elektronikoperatør",
    "Autolakerer",
    "Webudvikler",
    "Skiltetekniker",
    "Grafisk tekniker",
    "Eventkoordinator",
    "Multimedie integrator",
    "Multimedie animator",
    "Fotograf",
    "Mediegrafiker",
    "Film- og tv-produktionstekniker",
    "Film- og tv-assistent",
    "Klargøring og rangering af persontog",
    "Klargøring og rangering af godstog",
    "Godschauffør",
    "Kørselsdisponent",
    "Renovationschauffør",
    "Tankbilchauffør",
    "Flyttechauffør",
    "Lageroperatør til automatiserede lagre",
    "Lagermedhjælper",
    "Lager- og terminaldisponent",
    "Lager og transportoperatør",
    "Lager og logistikoperatør",
    "Ambulancebehandler",
    "Sikkerhedsvagt",
    "Landbrugsassistent",
    "Landmand, husdyr",
    "Landmand, planter",
    "Jordbrugsmaskinfører",
    "Produktionsleder",
    "Agrarøkonom",
    "Landmand, økologi",
    "Anlægsteknik",
    "Plejeteknik",
    "Dyr i zoologiske anlæg",
    "Forsøgsdyr",
    "Dyrehandel",
    "Hestemanager",
    "Veterinærsygeplejerske",
    "Skov- og naturplejer",
    "Skovbrugsmaskinfører",
    "Arborist",
    "Mejerist",
    "Svineslagter",
    "Slagter",
    "Groundsman",
    "Greenkeeper",
    "Tarmtekniker",
    "Gourmetslagter",
    "Butik/Delikatesse",
    "Pølsemager/Forædler",
    "Svine-/Kreaturslagter",
    "Ernæringsassistent",
    "Hospitalsservice",
    "Virksomhedsservice",
    "Rengøringstekniker",
    "Tjener",
    "Receptionist",
    "Kok",
    "Gastronomassistent",
    "Smørrebrød og catering",
    "Kok, grøn gastronomi",
    "Detailbager",
    "Håndværksbager",
    "Konditor",
    "Bagværker",
    "Urmager",
    "Profil aftagelig protetik",
    "Profil fast protetik",
    "Tandtekniker i fast protetik",
    "Tandtekniker i aftagelig protetik",
    "Tandklinikassistent",
    "Frisør",
    "Fysisk træning",
    "Fitness manager",
    "Hud- og skønhedsplejer",
    "Spa- og wellnessbehandler",
    "Beklædningshåndværker",
    "Tekstil- og beklædningsassistent",
    "Autosadelmager",
    "Møbelpolstrer",
    "Gardindekoratør",
    "Ortopædist",
    "Eventtekniker med speciale i audioteknik",
    "Eventtekniker med speciale i illuminationsteknik",
    "Teatertekniker",
    "Teater-, event- og av-teknisk produktionsassistent",
    "Av-tekniker",
    "Teknisk designer - bygge og anlæg",
    "Teknisk designer - industriel produktion",
    "Administration",
    "Økonomi",
    "Revision",
    "Offentlig administration",
    "Advokatsekretær",
    "Spedition og shipping",
    "Bank og realkredit",
    "Liv og pension",
    "Skadesforsikring",
    "Digital handel B2B",
    "B2B manager",
    "Logistikassistent",
    "Indkøbsassistent",
    "Handelsass., salg",
    "Handelsass., salg, branche: Auto",
    "Handelsass., salg, branche: VVS",
    "Handelsass., salg, branche: Stål",
    "Handelsass., salg, branche: Træ og byggematerialer",
    "Handelsass., salg, branche: Værktøj og værktøjsmas",
    "Handelsass., salg, branche: Landbrugsmaskiner",
    "Handelsass., salg, branche: El",
    "Handelsass., salg, profil: Storkundeprofil",
    "Salgsassistent",
    "Salgsassistent, Dagligvarer",
    "Convenience mad",
    "Convenience, bageriudsalg",
    "Convenience, Coffee shop",
    "Convenience",
    "Salgsassistent, Tekstil",
    "Salgsassistent, Tekstil, herretøj",
    "Salgsassistent, Tekstil, dametøj",
    "Salgsassistent, Byggemarked, værktøj og beslag",
    "Salgsassistent, Boghandel",
    "Salgsassistent, Fotohandel",
    "Salgsassistent, Guld, sølv og ure",
    "Salgsassistent, Glas, porcelæn og gaveartikler",
    "Salgsassistent, Legetøj og hobbyartikler",
    "Salgsassistent, Materialhandel",
    "Salgsassistent, Møbelhandel",
    "Salgsassistent, Sko og læderartikler",
    "Salgsassistent, Sport og fritid",
    "Salgsassistent, Kapitalkædedrift",
    "Salgsassistent, Stormagasin",
    "Salgsassistent, Forbrugerelektronik",
    "Salgsassistent, Optik",
    "Salgsassistent, Køkken og bad",
    "Dekoratør/ visual merchandiser",
    "Blomsterdekoratør",
    "Digital handel",
    "Retail Manager",
    "Pædagogisk assistent",
    "Social- og sundhedshjælper",
    "Social- og sundhedsassistent",
    "EUD optagelsesprøve",
    "Omsorg, sundhed og pædagogik",
    "Kontor, handel og forretningsservice",
    "Fødevarer, jordbrug og oplevelser",
    "Teknologi, byggeri og transport",
    "Individuel EUD, Omsorg, sundhed og pædagogik",
    "Indiv. EUD,   Kontor, handel og forretningsservice",
    "Individuel EUD, Fødevarer, jordbrug og oplevelser",
    "Individuel EUD, Teknologi, byggeri og transport",
    "Buschauffør",
    "Buschauffør i kollektiv trafik",
    "Kørselsdisponent",
    "Turistbuschauffør",
    "Gartner",
    "Kranfører",
    "Kørselsdisponent",
    "Produktør",
    "GF+ Omsorg, sundhed og pædagogik",
    "GF+ Kontor, handel og forretningsservice",
    "GF+ Fødevarer, jordbrug og oplevelser",
    "GF+ Teknologi, byggeri og transport",
    "Autohjælp",
    "Bådmekaniker",
    "Personvognsmontør",
    "Personvognsmekaniker",
    "Lastvognsmontør",
    "Lastvognsmekaniker",
    "Havnemedhjælper",
    "Havne- og terminalarbejder",
]
