# Generated by Django 4.2.3 on 2025-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="stars",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
