# Generated by Django 4.2.3 on 2025-10-27 12:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_workplace_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="stars",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=Decimal("0"),
                max_digits=2,
                null=True,
            ),
        ),
    ]
