# Generated by Django 4.2.3 on 2025-10-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workplaces", "0003_alter_workplace_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
                ("stars", models.DecimalField(decimal_places=1, max_digits=2)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workplaces.workplace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
