# Generated by Django 4.2.3 on 2025-10-28 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workplaces", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="verifiedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifiedWorkPlaceReviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
