# Generated by Django 4.2.3 on 2025-10-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0005_review_verifiedby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="stars",
        ),
    ]
