# Generated by Django 4.2.3 on 2025-10-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0006_remove_workplace_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="titel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
