# Generated by Django 4.2.3 on 2025-10-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0007_review_titel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="titel",
            new_name="title",
        ),
    ]
