# Generated by Django 4.2.3 on 2025-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0008_rename_titel_review_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(default="no comment"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(default="no title", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workplace",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
