# Generated by Django 4.2.3 on 2025-11-03 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0010_category_workplace_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="top_categories",
                        to="workplaces.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
