# Generated by Django 4.2.3 on 2025-11-03 09:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0011_topcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="topcategory",
            name="color",
            field=models.CharField(default=users.models.randomColor, max_length=32),
        ),
    ]
