# Generated by Django 4.2.3 on 2025-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0012_topcategory_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="website",
        ),
        migrations.AddField(
            model_name="workplace",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
